drone-lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
drone-server:
  scale: 1
  metadata:
    remote_driver: github
    remote_config: "https://github.com?client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET_KEY>"
    database_driver: postgres
    database_config: "postgres://postgres:<PASSWORD>@database:5432/postgres?sslmode=disable"
    http_proxy_on: "false"
    debug: "true"
  health_check:
    port: 1620
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET /ping HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
